@startuml
participant Actor
Actor -> GoodsService : buyCreate
activate GoodsService
GoodsService -> RedisUtil : set
activate RedisUtil
RedisUtil --> GoodsService
deactivate RedisUtil
GoodsService -> Producer : sendMsg
activate Producer
Producer --> GoodsService
deactivate Producer
return
@enduml