@startuml
participant Actor
Actor -> BuyService : buySeckill
activate BuyService
BuyService -> SeckillService : getSeckillByGid
activate SeckillService
SeckillService -> RedisUtil : hget
activate RedisUtil
RedisUtil --> SeckillService
deactivate RedisUtil
SeckillService -> SeckillDao : selectSeckillByGid
activate SeckillDao
SeckillDao --> SeckillService
deactivate SeckillDao
SeckillService -> RedisUtil : hset
activate RedisUtil
RedisUtil --> SeckillService
deactivate RedisUtil
SeckillService --> BuyService
deactivate SeckillService
BuyService -> SeckillService : editSeckill
activate SeckillService
SeckillService -> RedisUtil : hset
activate RedisUtil
RedisUtil --> SeckillService
deactivate RedisUtil
SeckillService -> SeckillDao : updateSeckill
activate SeckillDao
SeckillDao --> SeckillService
deactivate SeckillDao
SeckillService --> BuyService
deactivate SeckillService
BuyService -> Producer : sendMsg
activate Producer
Producer --> BuyService
deactivate Producer
return
@enduml